In [2]:
import numpy as np

arr = [1.15, 4, 2, 5, 3] #타입이 일치하지 않을 경우, 상위 타입으로 호환
n_arr = np.array(arr)

print(arr) 
print(n_arr) 

[1.15, 4, 2, 5, 3]
<class 'list'>
[1.15 4.   2.   5.   3.  ]
<class 'numpy.ndarray'>


In [3]:
arr = ['1.15', 4, 2, 5, 3] #상위 타입, string으로 호환
n_arr = np.array(arr)

print(arr) 
print(n_arr) 

['1.15', 4, 2, 5, 3]
<class 'list'>
['1.15' '4' '2' '5' '3']
<class 'numpy.ndarray'>


In [4]:
arr = [1, 4, 2, 5, 3] 
n_arr = np.array(arr, dtype='float32') #타입 지정, dtype

print(arr) 
print(n_arr) 

[1, 4, 2, 5, 3]
<class 'list'>
[1. 4. 2. 5. 3.]
<class 'numpy.ndarray'>


In [5]:
num = np.array([1,4,2,3,4])

#동일한 코드 ndim == len(num.shape)
print(num.ndim)
print(len(num.shape))

1
1


In [1]:
num = np.array([[1,4,2],[3,5,4]])

print(len(num)) #차원이 return
print(num.size) #원소의 개수가 return

2
6


In [6]:
num = np.array(1)

#인자 하나만 array에 넣으면 차원이 0
print(num)
print(num.ndim)
print(num.shape)

1
0
()


In [9]:
num = np.array([1,2,3,4,5])

#슬라이싱 결과는 참조 독립적으로 사용하고 싶으면, copy()
ref = num[1:4]
cpy = num[1:4].copy()
num[2]=10
print(ref)
print(cpy)

[ 2 10  4]
[2 3 4]


In [2]:
#0으로 채운 배열, zeros
print(np.zeros((2,2)))
print()

#1로 채운 배열, ones
print(np.ones((2,2)))
print()

#특정 수로 채운 배열, full
print(np.full((2,2), 7))

[[0. 0.]
 [0. 0.]]

[[1. 1.]
 [1. 1.]]

[[7 7]
 [7 7]]


In [3]:
#단위 행렬, eye
print(np.eye(2))
print()

#대각선의 위치 이동
print(np.eye(3, k=1))
print()

#단위 행렬, identity
print(np.identity(3))

[[1. 0.]
 [0. 1.]]

[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [6]:
#배열 생성 linespace(start, end, num=, endpoint=, retstep=) 자동적으로 step 설정
print(np.linspace(0, 1, num=5, endpoint=True, retstep=True))
print()

#range(start, end, step) step 설정
print(np.arange(0.4, 1.1, 0.1))

(array([0.  , 0.25, 0.5 , 0.75, 1.  ]), 0.25)

[0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [7]:
num = np.array([[1,2,3],[4,5,6]])

#transpose 첫번째 열이 첫번째 행으로 열과 행 전치
print(num.T)
print()

#reshape 원소 순서를 지키면서 행렬의 크기만 변화
print(num.reshape((3,2)))

[[1 4]
 [2 5]
 [3 6]]

[[1 2]
 [3 4]
 [5 6]]


In [12]:
num = np.array([[1,2,3],[4,5,6]])
print(num.swapaxes(0,1))
print()

#axis를 기준으로 stride만큼 건너뛰어 선택
num3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(num3.swapaxes(0,1))
print()
print(num3.swapaxes(1,2))
print()
print(num3.swapaxes(0,2))

[[1 4]
 [2 5]
 [3 6]]

[[[ 1  2  3]
  [ 7  8  9]]

 [[ 4  5  6]
  [10 11 12]]]

[[[ 1  4]
  [ 2  5]
  [ 3  6]]

 [[ 7 10]
  [ 8 11]
  [ 9 12]]]

[[[ 1  7]
  [ 4 10]]

 [[ 2  8]
  [ 5 11]]

 [[ 3  9]
  [ 6 12]]]


In [14]:
x = np.array([1,2,3])
y = np.array([3,2,1])

#concatenate 함수의 인자를 리스트로
print(np.concatenate([x,y]))

[1 2 3 3 2 1]


In [16]:
grid = np.array([[1,2,3],[4,5,6]])

#이차원 배열의 concat
print(np.concatenate([grid, grid]))
print()

#가로 축으로 concat 하고 싶을 때
print(np.concatenate([grid, grid], axis=1))

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]

[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


In [20]:
#세로 축으로 concat
print(np.vstack([grid, grid]))
print()

#가로 축으로 concat
print(np.hstack([grid, grid]))

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]

[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


In [21]:
x = np.array([0,1,2,3,4,5,6,7,8])

#index를 기준으로 split / index는 리스트 형태로 전달
x1, x2, x3 = np.split(x, [3,5])
print(x1, x2, x3)

[0 1 2] [3 4] [5 6 7 8]


In [27]:
grid = np.arange(16).reshape((4,4))

upper, lower = np.split(grid, [2]) #same as vsplit
print(upper)
print()
print(lower)

[[0 1 2 3]
 [4 5 6 7]]

[[ 8  9 10 11]
 [12 13 14 15]]


In [25]:
grid = np.arange(16).reshape((4,4))

upper, lower = np.vsplit(grid, [2])
print(upper)
print()
print(lower)

[[0 1 2 3]
 [4 5 6 7]]

[[ 8  9 10 11]
 [12 13 14 15]]


In [28]:
grid = np.arange(16).reshape((4,4))

upper, lower = np.split(grid, [2], axis=1) #same as hsplit
print(upper)
print()
print(lower)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]

[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [26]:
grid = np.arange(16).reshape((4,4))

left, right = np.hsplit(grid, [2])
print(left)
print()
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]

[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [29]:
arr = np.array([100,80,70,90,110])

arr = (arr-32)*(5/9)
print(arr)

[37.77777778 26.66666667 21.11111111 32.22222222 43.33333333]


In [32]:
arr = np.array([[100,80,70,90,60],[30,20,70,100,100]])

print(np.mean(arr))
print()
print(np.mean(arr, axis=0)) #세로축의 평균, 열의 평균
print()
print(np.mean(arr, axis=1)) #가로축의 평균, 행의 평균

72.0

[65. 50. 70. 95. 80.]

[80. 64.]


In [36]:
rng = np.random.RandomState(0)
x = rng.randint(10, size=(3,4))
print(x)
print()
print(np.count_nonzero(x<6, axis=1))

[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]

[4 2 2]


In [37]:
print(np.sum((x>=3)|(x<0))) #여러개의 조건을 걸고 싶을 때 비트 연산자 사용

10
