In [2]:
import numpy as np

arr = [1.15, 4, 2, 5, 3] #타입이 일치하지 않을 경우, 상위 타입으로 호환
n_arr = np.array(arr)

print(arr) 
print(n_arr) 

[1.15, 4, 2, 5, 3]
<class 'list'>
[1.15 4.   2.   5.   3.  ]
<class 'numpy.ndarray'>


In [3]:
arr = ['1.15', 4, 2, 5, 3] #상위 타입, string으로 호환
n_arr = np.array(arr)

print(arr) 
print(n_arr) 

['1.15', 4, 2, 5, 3]
<class 'list'>
['1.15' '4' '2' '5' '3']
<class 'numpy.ndarray'>


In [4]:
arr = [1, 4, 2, 5, 3] 
n_arr = np.array(arr, dtype='float32') #타입 지정, dtype

print(arr) 
print(n_arr) 

[1, 4, 2, 5, 3]
<class 'list'>
[1. 4. 2. 5. 3.]
<class 'numpy.ndarray'>


In [5]:
num = np.array([1,4,2,3,4])

#동일한 코드 ndim == len(num.shape)
print(num.ndim)
print(len(num.shape))

1
1


In [6]:
num = np.array(1)

#인자 하나만 array에 넣으면 차원이 0
print(num)
print(num.ndim)
print(num.shape)

1
0
()


In [9]:
num = np.array([1,2,3,4,5])

#슬라이싱 결과는 참조 독립적으로 사용하고 싶으면, copy()
ref = num[1:4]
cpy = num[1:4].copy()
num[2]=10
print(ref)
print(cpy)

[ 2 10  4]
[2 3 4]


In [16]:
#0으로 채운 배열, zeros
print(np.zeros((2,2)))

#1로 채운 배열, ones
print(np.ones((2,2)))

#특정 수로 채운 배열, full
print(np.full((2,2), 7))

[[0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]]
[[7 7]
 [7 7]]


In [17]:
#단위 행렬, eye
print(np.eye(2))

#대각선의 위치 이동
print(np.eye(3, k=1))

#단위 행렬, identity
print(np.identity(3))

[[1. 0.]
 [0. 1.]]
[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [2]:
#배열 생성 linespace(start, end, num=, endpoint=, retstep=) 자동적으로 step 설정
print(np.linspace(0, 1, num=5, endpoint=True))

#range(start, end, step) step 설정
print(np.arange(0.4, 1.1, 0.1))

[0.   0.25 0.5  0.75 1.  ]
[0.4 0.5 0.6 0.7 0.8 0.9 1. ]
